### PR TITLE
implemented query params for collectionendpoints

### PR DESCRIPTION
**Pull request by AndreasBieber**
Hi Basti,

this pull request provides support of query parameters on CollectionEndpoints.

Usage: 
```cs
server.Packages.ReadAllAsync(new { email = "john@contoso.com" });
```

And just a side note:
I've removed the optional parameters from the method `ReadAllAsync` for several reasons (i think the optional parameters should be also replaced on all other methods):

- Optional parameter values are baked into the method call site code, thus, if a default value has been changed, all referencing assemblies need to be rebuilt, otherwise the original values will be used.
- The CLS allows compilers to ignore default parameter values, and thus require the caller to explicitly specify the values.
- The concept of optional argument exists only in VB.Net and C#. In all other languages like C++ or Java, the overloading mechanism is the only way to get the same behavior.
- Optional parameters prevent muddying the definition of the function contract. Here is a simple example: if there are two optional parameters, when one is defined, is the second one still optional or mandatory?

If this is not ok for you, don't hesitate to revert this change.

Cheers
 Andy

### CODE REVIEW

**Comment by bastianeicher** [comment]
Hi Andy,

TypedRest supports [URI Templates](https://tools.ietf.org/html/rfc6570) via HTTP Headers or in JSON. I was thinking about using the [Form-Style Query Expansion](https://tools.ietf.org/html/rfc6570#section-3.2.8) feature of URI templates to support query parameters.

A Web API controller using [WebApi.LinkHeader](https://github.com/1and1/WebApi.LinkHeader) could look like this
```csharp
[HttpGet, Route("")]
[LinkHeader("search{?name,email}", Rel = "search", Templated = true)]
public IEnumerable<Package> ListAll() { /*...*/ }

[HttpGet, Route("search")]
public IEnumerable<Package> Search(string name, string email) { /*...*/ }
```

The accompanying TypedRest endpoint could have a method like this:
```csharp
public CollectionEndpoint<Package> Search(string name = null, string email = null)
{
  var template = LinkTemplate("search").GetResolver();
  if (name != null) template.Bind("name", name);
  if (email != null) template.Bind("email", email);
  return new CollectionEndpoint<Package>(this, relativeUri: template.Resolve());
}
```
or this:
```csharp
public CollectionEndpoint<Package> Search(IDictionary<string, object> parameters)
{
  return new CollectionEndpoint<Package>(this, relativeUri: LinkTemplate("search").Resolve(parameters));
}
```

The usage would look like this:
```csharp
var result = await server.Packages.Search(email: "john@contoso.com").ReadAllAsync();
```

On the topic of default methods:

 * I was careful to only use default values that represent a "zero" or "unset" state and therefor should never change. `default(CancellationToken)` is probably the best example.
 * I am willing to mainly target C# and VB consumers of the library, since other languages are extreme minorities on the CLR. That being said, quite a few smaller languages such as IronPython have full support for optional parameters. Vanilla C++ also has this feature and calls it default arguments.
 * The [Java version of TypedRest](https://github.com/1and1/TypedRest-Java) does indeed use classic overloading instead.
 * In my opinion using named parameters helps keep different combinations of optional parameters easily readable.

Regards
Bastian

**Comment by AndreasBieber** [comment]
Hi Basti,

very nice approach. And i think it should be definitly implemented in TypedRest. 

But what about 3rd party APIs which don't support those links? I think both of our solutions should be implemented, so that consumers can also use TypedRest with filter queries on 3rd party APIs which don't support those links.

What do you think?

Cheers,
Andy

**Comment by bastianeicher** [comment]
Hi Andy,

the template-based approach should already work with the current release of TypedRest.

I've just added a new feature in commit 46380427 that allows you to specify default links and link templates on the client-side for APIs that do not send `Link` headers. You could add something like this to the constructor of an endpoint:
```csharp
AddDefaultLinkTemplate("search{?name,email}", rel: "search");
```

The advantage of using this combined with a custom method defined in the endpoint class (like the `Search()` example above) rather than TypedRest itself is additional type-safety. The endpoint "knows" exactly which parameters are acceptable and passing in anything else would lead to a compiler error.

Another nice side-effect is that if the server ever did start setting the `Link` header that value would override the client-side default.

Here is a more complete sample:
```csharp
public class PackageCollectionEndpoint : CollectionEndpoint<Package>
{
  public PackageCollectionEndpoint(IEndpoint parent)
    : base(parent, relativeUri: "packages")
  {
    AddDefaultLinkTemplate("search{?name,email}", rel: "search");
  }

  public CollectionEndpoint<Package> Search(string name = null, string email = null)
  {
    return new CollectionEndpoint<Package>(this, LinkTemplate("search").Resolve(new Dictionary<string, object>
    {
      ["name"] = name,
      ["email"] = email
    }));
  }
}
```

Perhaps we could re-purpose your anonymous class code to to make the template resolving nicer:
```csharp
LinkTemplate("search").Resolve(new {name, email});
```

Regards
Bastian

**Comment by bastianeicher** [comment]
I've added support for `.Resolve()` with anonymous classes in commit e670c8b9.
I also created an upstream pull request for the URI Template library embedded in TypedRest at a7b0/uri-templates#4.

I'll look at integrating the reflection caching logic of `PropertyHelper` more globally in a future commit.

**Comment by AndreasBieber** [comment]
Seems to be the best solutions. Thank you.

**Pull request closed without merging**
