### PR TITLE
Feature: TriggerAsync with entities and/or returning a result

### PR DESCRIPTION
**Pull request by AndreasBieber**
Hi Basti,

i've implemented three new `TriggerAsync` methods to be able to trigger events on an API containing a body/entity and/or returning a result.

Example:
`/api/send`
`TriggerAsync<EmailMessage,Status>(mailMessage);`

Cheers,
 Andy

### CODE REVIEW

**Comment by bastianeicher** [comment]
Hi Andy,

I really like the idea of a `TriggerEndpoint` that also takes and/or returns an entity. But perhaps it would be better to implement this in a separate `TriggerEndpoint<TEntity>` class? This way the consumer of the class would be forced to pass in the correct/expected entity type, rather than allowing different different type values for each call to `.TriggerAsync<TEntity>(...)`. What do you think?

Regards
Bastian

**Comment by AndreasBieber** [comment]
Hi Basti,

well, that's a good point. But what about `TriggerEndpoint`s which are only returning an entity but don't accept entities?

Cheers,
 Andy

**Comment by bastianeicher** [comment]
Good point! How about this:

No input entity:
 * `TriggerEndpoint` (no result entity)
 * `TriggerEndpoint<TResult>` (with result entity)

With input entity:
 * `ProcessEndpoint<TInput>` (no result entity)
 * `ProcessEndpoint<TInput, TResult>` (with result entity)

**Comment by AndreasBieber** [comment]
Hi Basti,

i think your solution would be the best one. But i'm not sure whether `ProcessEndpoint` is a good name, because a `Trigger` _triggers_ a process, right? That can be confuse the consumer.

Maybe we just name the `ProcessEndpoint` -> `TriggerEndpointWithEntity`?

Cheers,
 Andy

**Comment by bastianeicher** [comment]
My thinking was that a `ProcessEndpoint` *processes* an entity (like processing an order) while a `TriggerEndpoint` is only *triggered* without any additional parameters (like pulling a trigger).

But you are right, the name `Process` by itself could be confusing. Maybe `ProcessingEndpoint<T>`?

**Comment by AndreasBieber** [comment]
Hi Basti,

IMHO it'll be still confusing as for the same reason as i already mentioned:

> A `TriggerEndpoint` **_triggers_** a **_process_** which is **_processing_** some workflow.

and on the other side:

> A `ProcessingEndpoint` **_triggers_** a **_process_** with an _**entity**_ which is **_processing_** some workflow.

As i have no other idea than naming it `TriggerEndpointWithEntity`, you as the owner have to decide ;-)

Cheers, 
 Andy

**Comment by bastianeicher** [comment]
I think I've finally come up with the "perfect" solution. ;)

* `ActionEndpoint` for no input/output, like .NET's `Action` delegate type, replacing `TriggerEndpoint`
* `ActionEndpoint<TEntity>` for input-only, like .NET's `Action<T>` delegate type
* `FunctionEndpoint<TResult>` for output-only, like .NET's `Func<TResult>` delegate type
* `FunctionEndpoint<TEntity, TResult>` for input and output, like .NET's `Func<T, TResult>` delegate type

**Comment by AndreasBieber** [comment]
Awsome! 

If it's ok for you, i'll implement it.

Cheers,
 Andy

**Comment by AndreasBieber** [comment]
Would be cool if you can make a release after this merge, so that i'm able to use from nuget in my project.

Thank you for your support.

Cheers,
 Andy

**Comment by bastianeicher** [comment]
Thanks a lot. I have merged your changes and did some additional refactoring.

I just pushed out v0.15.0.0 to NuGet.

**Pull request closed without merging**
